//write a program to swap two numbers without using third variable

public class P10 {


    public static void main(String[] args) {
    int a=3;
    int b=5;
        System.out.println("before swap");
        System.out.println("a = "+a);
        System.out.println("b = "+b);
        a=a+b;
        b=a-b;
        a=a-b;
        System.out.println("after swap");
        System.out.println("a = "+a);
        System.out.println("b = "+b);




    }
    }
